CREATE SEQUENCE IF NOT EXISTS event_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE event
(
    id            BIGINT NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    event_type_id BIGINT,
    start_date    TIMESTAMP WITHOUT TIME ZONE,
    end_date      TIMESTAMP WITHOUT TIME ZONE,
    user_id       BIGINT,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE event_status
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_event_status PRIMARY KEY (id)
);

CREATE TABLE event_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_event_type PRIMARY KEY (id)
);

CREATE TABLE posting_location
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_posting_location PRIMARY KEY (id)
);

CREATE TABLE product_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_product_type PRIMARY KEY (id)
);

CREATE TABLE rank
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    abbreviation VARCHAR(255),
    CONSTRAINT pk_rank PRIMARY KEY (id)
);

CREATE TABLE theme
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_theme PRIMARY KEY (id)
);

CREATE TABLE theme_example
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    theme_id    BIGINT,
    CONSTRAINT pk_theme_example PRIMARY KEY (id)
);

CREATE TABLE unit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    parent_id BIGINT,
    CONSTRAINT pk_unit PRIMARY KEY (id)
);

CREATE TABLE user_profile
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    role       VARCHAR(255)                            NOT NULL,
    unit_id    BIGINT                                  NOT NULL,
    rank_id    BIGINT,
    CONSTRAINT pk_user_profile PRIMARY KEY (id)
);

ALTER TABLE unit
    ADD CONSTRAINT uc_unit_name UNIQUE (name);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_EVENT_TYPE FOREIGN KEY (event_type_id) REFERENCES event_type (id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_USER FOREIGN KEY (user_id) REFERENCES user_profile (id);

ALTER TABLE theme_example
    ADD CONSTRAINT FK_THEME_EXAMPLE_ON_THEME FOREIGN KEY (theme_id) REFERENCES theme (id);

ALTER TABLE user_profile
    ADD CONSTRAINT FK_USER_PROFILE_ON_RANK FOREIGN KEY (rank_id) REFERENCES rank (id);

ALTER TABLE user_profile
    ADD CONSTRAINT FK_USER_PROFILE_ON_UNIT FOREIGN KEY (unit_id) REFERENCES unit (id);